

services:
  whatsapp-transcribe:
    build: .
    restart: always
    env_file: .env
    ports:
      - 80:80

  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
