

services:
  whatsapp-transcribe:
    build: .
    restart: always
    env_file: .env
    volumes:
      - model_cache:/backend/.model_cache/

    ports:
      - 80:80

  tunnel:
    image: cloudflare/cloudflared
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN


volumes:
  model_cache:
